// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WFrMeDg7R0SmI_HRdds2lkTPKmkW9f4',
    appId: '1:756207872812:web:deae18211bcd0480685a89',
    messagingSenderId: '756207872812',
    projectId: 'salesforce-authenticatio-892b5',
    authDomain: 'salesforce-authenticatio-892b5.firebaseapp.com',
    storageBucket: 'salesforce-authenticatio-892b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9VkWbJ5HcUWCurH1MEoLhu614G97kels',
    appId: '1:756207872812:android:ae7c85ef016f7585685a89',
    messagingSenderId: '756207872812',
    projectId: 'salesforce-authenticatio-892b5',
    storageBucket: 'salesforce-authenticatio-892b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtybhl2q5GdQGrpq9XIIK_jekbPQN4Ks',
    appId: '1:756207872812:ios:72abd6a1e633505e685a89',
    messagingSenderId: '756207872812',
    projectId: 'salesforce-authenticatio-892b5',
    storageBucket: 'salesforce-authenticatio-892b5.appspot.com',
    iosBundleId: 'com.example.salesforce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHtybhl2q5GdQGrpq9XIIK_jekbPQN4Ks',
    appId: '1:756207872812:ios:458764a6d2ce7b25685a89',
    messagingSenderId: '756207872812',
    projectId: 'salesforce-authenticatio-892b5',
    storageBucket: 'salesforce-authenticatio-892b5.appspot.com',
    iosBundleId: 'com.example.salesforce.RunnerTests',
  );
}
